package com.azmqalabs.edaattestautomation.apppages.collectionofpages;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.PageFactory;
import com.aventstack.extentreports.ExtentTest;
import com.azmqalabs.edaattestautomation.apppages.biller.pages.*;
import com.azmqalabs.edaattestautomation.common.DBConnect;
import com.azmqalabs.edaattestautomation.common.uielement.fieldDecorator;
import com.azmqalabs.edaattestautomation.apppages.admin.pages.*;
public class Pages{
	private WebDriver driver;
	private ExtentTest test;
	public BillerLoginPage BillerLoginPage;
	public DBConnect DBConnect;
	public InvokeApplicationPage InvokeApplicationPage;
	public BillerIndividualClientPage BillerIndividualClientPage;
	public BillerSubbillerPage BillerSubbillerPage;
	public BillerSettingsPage BillerSettingsPage;
	public BillerSignUpPage BillerSignUpPage;
	public BillerReceivablesExportedbillsPage BillerReceivablesExportedbillsPage;
	public BillerSettingsDiscountPage BillerSettingsDiscountPage;
	public BillerUserMngUserListPage BillerUserMngUserListPage;
	public BillerSystemMangement BillerSystemMangement;
	public AdminCorporatePage AdminCorporatePage;
	public AdminIndividualClientPage AdminIndividualClientPage;
	public AdminInvokeApplicationPage AdminInvokeApplicationPage;
	public AdminLoginPage AdminLoginPage;
	public AdminReceivablesExportedbillsPage AdminReceivablesExportedbillsPage;
	public AdminSettingsDiscountPage AdminSettingsDiscountPage;
	public AdminSettingsPage AdminSettingsPage;
	public AdminSubbillerPage AdminSubbillerPage;
	public AdminSystemMangement AdminSystemMangement;
	public AdminUserMngUserListPage AdminUserMngUserListPage;
	public AdminSignUpPage AdminSignUpPage;
	public AdminNotApprovedBillerManagement AdminNotApprovedBillerManagement;
	public AdminApprovedBillerManagement AdminApprovedBillerManagement;
	public AdminTrackerBillerManagementPage AdminTrackerBillerManagementPage;
	public MyBillsPage MyBillsPage;
	public BillerUserGroupManagementPage BillerUserGroupManagementPage;
	public BillerCorporatePage BillerCorporatePage;
	public FlipkartPage FlipkartPage;
	public BikeRacePage BikeRacePage;
	public AqarekPlatformPage AqarekPlatformPage;

public Pages(WebDriver driver,ExtentTest test){
		this.driver=driver;
		this.test=test;
		PageFactory.initElements(new fieldDecorator(driver,test), this);
		DBConnect= new DBConnect(driver,test);
		InvokeApplicationPage = new InvokeApplicationPage(driver,test);
		BillerLoginPage = new  BillerLoginPage(driver,test);
		BillerIndividualClientPage = new  BillerIndividualClientPage(driver,test);
		BillerSettingsPage =new  BillerSettingsPage(driver,test);
		BillerSubbillerPage=new  BillerSubbillerPage(driver,test);
		BillerSignUpPage=new  BillerSignUpPage(driver,test);
		BillerCorporatePage= new BillerCorporatePage(driver,test);
		BillerReceivablesExportedbillsPage= new BillerReceivablesExportedbillsPage(driver,test);
		BillerSettingsDiscountPage= new BillerSettingsDiscountPage(driver,test);
		BillerUserMngUserListPage= new BillerUserMngUserListPage(driver,test);
		BillerSystemMangement=new BillerSystemMangement(driver, test);
		AdminCorporatePage=new AdminCorporatePage(driver, test);
		AdminIndividualClientPage =new  AdminIndividualClientPage(driver,test);
		AdminInvokeApplicationPage=new  AdminInvokeApplicationPage(driver,test);
		AdminLoginPage=new  AdminLoginPage(driver,test);
		AdminReceivablesExportedbillsPage= new AdminReceivablesExportedbillsPage(driver,test);
		AdminSettingsDiscountPage= new AdminSettingsDiscountPage(driver,test);
		AdminSettingsPage= new AdminSettingsPage(driver,test);
		AdminSubbillerPage= new AdminSubbillerPage(driver,test);
		AdminSystemMangement=new AdminSystemMangement(driver, test);
		AdminUserMngUserListPage=new AdminUserMngUserListPage(driver, test);
		AdminSignUpPage=new AdminSignUpPage(driver, test);
		AdminNotApprovedBillerManagement=new AdminNotApprovedBillerManagement(driver, test);
		AdminApprovedBillerManagement=new AdminApprovedBillerManagement(driver, test);
		AdminTrackerBillerManagementPage=new AdminTrackerBillerManagementPage(driver, test);
		MyBillsPage=new MyBillsPage(driver, test);;
		BillerUserGroupManagementPage=new BillerUserGroupManagementPage(driver, test);;
		FlipkartPage =new FlipkartPage(driver, test);
		BikeRacePage = new BikeRacePage(driver, test);
		AqarekPlatformPage = new AqarekPlatformPage(driver, test);
}
}
